#!/usr/bin/env python3
"""Merge per-shard pattern-recognition logs into one per-ticker verdict log.

Sources: logs/pattern_recognition_<T>_<arm>.log (shards). AAPL gbm1y comes
from the original single-process logs/pattern_recognition.log (5-year run,
same code path for the gbm arms). The original AAPL knn cells are NOT used:
they were produced by the unsorted-top-k defect (k=50/200 were arbitrary
subsets of the 500 nearest).
Writes logs/pattern_recognition_merged.log (per-ticker cells + one FINAL
line per ticker) and findings/pattern_recognition.md. One command:

  cd /opt/Warden/trading && ./bin/python webapp/pattern_recognition_merge.py
"""
import json
from pathlib import Path

LOGS = Path("/opt/Warden/trading/logs")
TICKERS = ["AAPL", "MSFT", "NVDA", "MU", "TXN", "V", "JPM", "GEV", "CVX", "KO"]
ARMS = ["knn", "gbm1y", "gbmall"]


def rows(path: Path):
    out = []
    if not path.exists():
        return out
    for ln in path.read_text().splitlines():
        try:
            r = json.loads(ln)
        except ValueError:
            continue
        if isinstance(r, dict):
            out.append(r)
    return out


def cells_for(t: str, arm: str):
    src = LOGS / f"pattern_recognition_{t}_{arm}.log"
    rs = rows(src)
    if t == "AAPL" and arm == "gbm1y" and not rs:
        rs, src = rows(LOGS / "pattern_recognition.log"), LOGS / "pattern_recognition.log"
    hdr = next((r for r in rs if r.get("ticker") == t and "sessions" in r), None)
    if arm == "knn":
        c = {}
        for r in rs:
            if r.get("ticker") == t and r.get("signal") == "knn" and "k" in r:
                c[r["k"]] = r                      # last occurrence wins
        return hdr, [c[k] for k in sorted(c)], src
    c = [r for r in rs if r.get("ticker") == t and r.get("signal") == "gbm"
         and r.get("arm") == arm[3:]]
    return hdr, c[-1:], src


def main():
    merged = []
    table = ["| ticker | arm | trades | dir % | avg net bps | folds net bps (old→new) | +folds | PASS |",
             "|---|---|---|---|---|---|---|---|"]
    for t in TICKERS:
        hdrs, passes, missing = set(), [], []
        for arm in ARMS:
            hdr, cs, src = cells_for(t, arm)
            if hdr:
                hdrs.add((hdr["sessions"], hdr["bars"], hdr["history_from"]))
            if not cs:
                missing.append(arm)
                continue
            for c in cs:
                merged.append({**c, "source": src.name})
                name = f"knn k={c['k']}" if arm == "knn" else arm
                folds = [f["net_bps"] for f in c["folds"]]
                table.append(f"| {t} | {name} | {c['trades']} | {c['dir_pct']} | {c['avg_net_bps']} | "
                             f"{' / '.join(str(round(x)) for x in folds)} | "
                             f"{sum(1 for x in folds if x > 0)}/4 | {'**PASS**' if c['PASS'] else 'fail'} |")
                if c["PASS"]:
                    passes.append(name)
        final = {"ticker": t, "FINAL": True, "history": sorted(hdrs),
                 "gate_passes": passes, "missing_arms": missing,
                 "verdict": ("INCOMPLETE" if missing else
                             ("GATE PASS -> stress pending" if passes else "no cell passed the gate"))}
        merged.append(final)
    (LOGS / "pattern_recognition_merged.log").write_text("\n".join(json.dumps(r) for r in merged) + "\n")
    finals = [r for r in merged if r.get("FINAL")]
    # gbm1y vs gbmall: does more history help or dilute?
    cmp = ["| ticker | gbm1y dir% / net | gbmall dir% / net | more history |", "|---|---|---|---|"]
    better = worse = 0
    for t in TICKERS:
        a = next((r for r in merged if r.get("ticker") == t and r.get("arm") == "1y"), None)
        b = next((r for r in merged if r.get("ticker") == t and r.get("arm") == "all"), None)
        if not a or not b or a["avg_net_bps"] is None or b["avg_net_bps"] is None:
            cmp.append(f"| {t} | {a and a['dir_pct']} | {b and b['dir_pct']} | incomplete |")
            continue
        d = b["avg_net_bps"] - a["avg_net_bps"]
        better += d > 0
        worse += d < 0
        cmp.append(f"| {t} | {a['dir_pct']} / {a['avg_net_bps']} | {b['dir_pct']} / {b['avg_net_bps']} | "
                   f"{'helps' if d > 0 else 'dilutes'} ({d:+.2f} bps) |")
    n_pass = sum(len(f["gate_passes"]) for f in finals)
    n_cells = sum(1 for r in merged if "PASS" in r)
    incomplete = [f["ticker"] for f in finals if f["missing_arms"]]
    md = [
        "# Pattern recognition (k-NN window matching + 1y-vs-all GBM) — results",
        "",
        "Generated by `webapp/pattern_recognition_merge.py` from the shard logs "
        "`logs/pattern_recognition_<T>_<arm>.log` (merged: `logs/pattern_recognition_merged.log`).",
        "Honest gate: 4 prior-only folds over the last 100 sessions, dir >= 51% over all fired bars, "
        "avg net > 0 after 2.0 bps/side, >= 3/4 folds positive incl. the oldest, >= 30 trades. Per ticker.",
        "",
        f"**Gate passes: {n_pass} of {n_cells} cells.**" + (f" INCOMPLETE tickers: {', '.join(incomplete)}." if incomplete else ""),
        "Stress (`--stress`, pre-registered) is only run for gate-passing cells; with no pass there is nothing to stress.",
        "",
        "Method note: the original single-process run's k-NN k=50/k=200 cells (AAPL) were invalid — `topk_dot` "
        "returned the 500 nearest in arbitrary argpartition order, so 'k=50' was 50 arbitrary members of the "
        "500 nearest. Fixed (neighbors sorted nearest-first, exact float64 re-rank, deterministic tie-break); "
        "k=500 is order-invariant and reproduces the old numbers.",
        "",
        "## Per ticker x arm",
        "",
        *table,
        "",
        "## Does more history help or dilute? (gbm1y vs gbmall, same folds)",
        "",
        *cmp,
        "",
        f"More history improved avg net bps on {better} tickers and worsened it on {worse}. "
        "Either way no GBM arm passes the gate unless marked PASS above.",
        "",
        "## Per-ticker verdicts",
        "",
        *[f"- {f['ticker']}: {f['verdict']}" + (f" ({', '.join(f['gate_passes'])})" if f['gate_passes'] else "")
          for f in finals],
        "",
    ]
    out = Path("/opt/Warden/trading/findings/pattern_recognition.md")
    out.write_text("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
